'use strict';var h=void 0,k=!0,m=null,n=!1;function p(a){this.d=k;this.D={};try{if(!localStorage.getItem("version")&&(localStorage.setItem("version",a),!localStorage.getItem("version")))throw"bomb";}catch(b){this.d=n}this.d?Number(localStorage.getItem("version"))!==a&&(localStorage.clear(),console.log("Storage cleared because of game update to version "+a)):this.setItem("version",a)}p.prototype.setItem=function(a,b){var c=JSON.stringify(b);this.d?localStorage.setItem(a,c):this.D[a]=c};
p.prototype.removeItem=function(a){this.d?localStorage.removeItem(a):delete this.D[a]};p.prototype.getItem=function(a){return this.d?JSON.parse(localStorage.getItem(a)):this.D[a]?JSON.parse(this.D[a]):m};Object.J=function(a){function b(a,c,g,v){var q;if("object"==typeof a){if(a==m)return a;for(q in d)if(d[q]===a)return f.push({resolveTo:q,child:g,i:v}),m;d[c]=a;Object.isArray(a)?g=[]:(g={},g.__proto__=a.__proto__);for(q in a)g[q]=b(a[q],c+"["+q+"]",g,q);e[c]=g}else g=a;return g}var c,d={},e={},f=[];a=b(a,"*");for(c in f){var g=f[c];g&&(g.V&&g.la in g.V)&&(g.V[g.la]=e[g.Oa])}return a};var s=800,t=600,u="level1.js",w="use_audio",x="last_level";window.addEventListener("load",function(){var a=new y;"localhost"===location.host&&window.za&&new LevelEditor(a)},n);
function y(){this.version=0.01;this.width=s;this.height=t;window.Ea=this;this.j=new p(this.version);this.j.d||z("localStorage not supported. Your game will not be saved.");this.pa=new A(this);this.N=new B(this);this.b=new C(!!this.j.getItem(w));this.b.d||z("Your browser does not support HTML5 audio or ogg/vorbis");this.g=this.f=this.s=this.r=m;this.Z=Date.now();this.n=0;this.A=this.v=this.z=this.Q=this.L=this.B=this.u=this.e=this.direction=this.t=this.h=this.ea=m;this.images={};this.ka=m;this.K=this.j.getItem(x);
this.K||(this.K=u);D(this,this.K)}function D(a,b){aa("levels/"+b+"?"+Math.random(),function(b){b=eval(b);if(!b)throw"level not found";a.a=b;ba(a,b)})}y.prototype.start=function(){this.u=E(this.images.charHitmap);this.o=n;F(this);this.sa||(this.sa=k,ca(this,this))};function F(a){a.r=a.a.ua.x;a.s=a.a.ua.y;a.f=a.a.ta.x;a.g=a.a.ta.y;a.h=2;a.direction=0;a.o=n;a.A=n;a.t=k;a.e=0;a.b.play(a.a.fa,k,k);a.b.stop(a.a.ga);a.ea=0;a.ka={};da(a);var b=a.j.getItem("state");b&&a.a.Ia(a,b)}
function da(a){var b=Object.J(a.a.B);a.B=[];a.L={};a.Q=[];a.z=[];a.v=[];b=H(b,function(a){return ea(a.position).map(function(b){var e=Object.J(a);e.f=b.x;e.g=b.y;return e})});b.forEach(function(b){var d=b.X||!!b.id,e=b.shape,f=b.P,g=h,l=h,G=h,r=h,v="posX posY dynamic trigger image blocking killing id tickFunction zIndex position shape".split(" ");I(Object.keys(b),v).length&&(console.log(I(Object.keys(b),v)),J(n,"Unkown properties"));b.m&&(g=a.images[b.m],J(g,"invalid image id"),e===h&&(e=new fa(g)));
J(!b.U||!f,"an object cannot block and have a trigger at the same time");b.Ha&&(J(!f,"an object cannot kill and have a trigger at the same time"),J(!b.U,"an object cannot kill and block at the same time"),f=a.W.bind(a));e&&(l=e.width,G=e.height,r=e,r.k||(r.k=E(r.m)),r=r.k);d={x:b.f,y:b.g,width:l,height:G,X:d,visible:k,m:g,k:r,P:f,zIndex:b.zIndex||0,F:b.F};f&&(J(f instanceof Function,"trigger has to be a function"),J(e,"objects that kill or have a trigger require a shape"),a.Q.push(d));b.m&&a.v.push(d);
b.U&&(J(e,"objects that block require a shape"),a.z.push(d));a.B.push(d);b.id&&(J(!a.L[b.id],"id used twice"),a.L[b.id]=d)});b=ga(a.v,function(a){return a.X});a.v=b[0];ha(a.N,b[1]);ia(a.N)}y.prototype.O=function(){this.b.O();this.b.muted?this.j.removeItem(w):this.j.setItem(w,1)};y.prototype.W=function(){this.o||(this.b.stop(this.a.fa),this.b.play(this.a.ga,n,k),this.o=k)};
function ba(a,b){function c(){g++;return function(){g--;0===g&&l.start()}}function d(){throw"loading a resource failed. Will not start";}var e=b.Pa,f=Object.keys(b.images),g=0,l=a;a.b.path=b.Ka;a.a=b;K(a.b,a.a.na,c(),d);K(a.b,a.a.oa,c(),d);f.forEach(function(a){var g=b.images[a],f=new Image;l.images[a]=f;f.onload=c();f.onerror=d;f.src=e+g})}var ca=function ja(b,c){var d=c.a,e=Date.now();c.n+=e-c.Z;c.Z=e;500<=c.n&&(console.log("logic skip"),c.n=0);for(;c.n>=d.ba.va;)ka(c),c.n-=d.ba.va;la(c.N);requestAnimationFrame(function(){ja(c)})};
function ka(a){var b=a.a.ba,c=a.pa.Y;a.a.F(a);a.Q.forEach(function(b){b.k&&b.P&&a.u.H(b.k,Math.round(b.x-a.f),Math.round(b.y-a.g))&&b.P.call(b,a)});a.B.forEach(function(b){b.F&&b.F.call(b,a)});a.ea++;if(!a.o)if(!c[L]!==!c[M]?(a.A=k,c[L]?(N(a,-b.qa),a.direction=1):c[M]&&(N(a,b.qa),a.direction=0)):a.A=n,0===a.h)c[O]&&(a.b.play(a.a.na,n,n,0.6),a.h=1,a.t=k,a.e=b.ma,a.w=b.w),P(a,1)||(a.h=2,a.t=k);else{if(1===a.h){if(a.e+=b.Ga,a.w--,!c[O]||0===a.w)a.h=2}else a.t&&c[O]&&(a.b.play(a.a.oa,n,n,0.6),a.h=1,a.t=
n,a.e=b.ma/1.5,a.w=b.w),a.e=a.e<b.ia?a.e+b.Ba:b.ia;P(a,Math.ra(a.e))&&(0<a.e?(a.h=0,a.e=0,c[O]=n):a.e=0)}}function N(a,b){if(0!==b){var c=Math.C(b);for(a.u.slice(0,0,1,a.a.Aa);b;)if(a.f+=c,b-=c,Q(a.u,a.z,a.f,a.g)){a.f-=c;break}}}function P(a,b){if(0===b)return n;for(var c=Math.C(b);b;)if(a.g+=c,b-=c,Q(a.u,a.z,a.f,a.g))return a.g-=c,k;return n};function C(a){this.muted=!a;this.d=k;window.ya?(new Audio).canPlayType("audio/ogg; codecs=vorbis")||(this.d=n):this.d=n;this.q=[];this.M=[]}
C.prototype.play=function(a,b,c,d,e){function f(a){return(a.b.ended||a.b.paused)!=!!c}if(this.d)if(this.muted)this.M.push([new Date,Array.wa(arguments)]);else{var g=this.q.filter(Function.G(a)).find(f),l;g?l=g.b:(l=new Audio(this.path+a),this.q.push({b:l,file:a}));g=n;e!==h?l.duration&&l.duration<e&&(g=k):e=0;g||(d!==h&&(l.volume=d),4>l.readyState?l.addEventListener("loadedmetadata",function(){l.currentTime=e}):l.currentTime=e,l.loop=b,l.play())}};
function K(a,b,c,d){if(a.d&&!a.muted)if(a.q.find(Function.G(b)))c&&setTimeout(c,0);else{var e=new Audio(a.path+b);e.muted=a.muted;c&&(e.addEventListener("canplaythrough",c),d&&e.addEventListener("error",d));e.load();a.q.push({b:e,file:b})}else setTimeout(c,0)}C.prototype.stop=function(a){function b(a){a.b.pause()}this.d&&this.q.filter(Function.G(a)).forEach(b)};
C.prototype.O=function(){function a(a){a.b.muted=b}if(this.d){var b=this.muted=!this.muted;this.q.forEach(a)}if(!this.muted){var c=this;this.M.forEach(function(a){a[1][4]=(Date.now()-a[0])/1E3;c.play.apply(c,a[1])});this.M=[]}};function R(a,b){this.width=a;this.height=b;this.count=a*b;this.data=new Uint8Array(this.count)}function E(a){var b=a.width,c=a.height,d=new R(b,c),e=document.createElement("canvas"),f=e.getContext("2d");e.width=b;e.height=c;f.clearRect(0,0,b,c);f.drawImage(a,0,0);a=f.getImageData(0,0,b,c).data;for(b=0;b<d.count;b++)d.data[b]=0<a[4*b+3]|0;return d}
R.prototype.stringify=function(){for(var a="Bitmap  width="+this.width+" height="+this.height+"\n",b=0;b<this.height;b++){for(var c=0;c<this.width;c++)a+=String(this.data[b*this.width+c]);a+="\n"}return a};function S(a,b,c,d,e){d=d||0;e=e||0;var f=Math.max(0,d),g=Math.max(0,e);d=Math.max(0,-d);e=Math.max(0,-e);return{ca:f,da:g,$:d,aa:e,width:Math.max(0,Math.min(a.width-f,b-d)),height:Math.max(0,Math.min(a.height-g,c-e))}}
R.prototype.slice=function(a,b,c,d){c=S(this,a,b,c,d);b=new R(a,b);d=c.da*this.width+c.ca;for(var e=c.aa*a+c.$,f=0;f<c.height;f++){for(var g=0;g<c.width;g++)b.data[e]=this.data[d],d++,e++;d+=this.width-c.width;e+=a-c.width}return b};R.prototype.H=function(a,b,c){b=S(this,a.width,a.height,b,c);c=b.aa*a.width+b.$;for(var d=b.da*this.width+b.ca,e=0;e<b.height;e++){for(var f=0;f<b.width;f++){if(this.data[d]&&a.data[c])return k;c++;d++}c+=a.width-b.width;d+=this.width-b.width}return n};
function Q(a,b,c,d){return b.some(function(b){return a.H(b.k,b.x-c,b.y-d)})};function fa(a){this.width=a.width;this.height=a.height;this.m=a;this.k=m};var L=37,M=39,O=32,T=82,U=77,V=84,W="keyboard_settings";
function A(a){this.p={};this.Y={};this.c=a;(a=a.j.getItem(W))?this.l=a:X(this);window.addEventListener("keydown",this.onkeydown.bind(this),n);window.addEventListener("keyup",this.onkeyup.bind(this),n);window.addEventListener("blur",this.onblur.bind(this),n);var b=this;document.getElementById("reset_keys").addEventListener("click",function(){X(b);b.c.j.setItem(W,b.l)},n);[["left",L],["right",M],["shoot",V],["jump",O],["mute",U],["restart",T]].forEach(function(a){var d=a[1],e=document.getElementById("keys"),
f=document.getElementById("press_key_msg");document.getElementById("change_"+a[0]).addEventListener("click",function(){e.style.display="none";f.style.display="block";window.addEventListener("keydown",function l(a){27!==a.which&&(Object.ha(b.l,d),b.l[a.which]=d,b.c.j.setItem(W,b.l));window.removeEventListener("keydown",l,n);e.style.display="block";f.style.display="none";a.preventDefault()},n)},n)})}function X(a){a.l={38:38,40:40,37:L,39:M,32:O,82:T,77:U,84:V,81:81}}
function Y(a,b){return!(b.ctrlKey||b.altKey||b.metaKey||b.target instanceof HTMLTextAreaElement||b.target instanceof HTMLInputElement||!a.l[b.which])}A.prototype.onkeydown=function(a){this.p[a.which]?a.preventDefault():Y(this,a)&&(this.p[a.which]=k,Z(this,n,a.which),a.preventDefault())};A.prototype.onkeyup=function(a){Y(this,a)&&(this.p[a.which]=n,Z(this,k,a.which),a.preventDefault())};
A.prototype.onblur=function(){for(var a=Object.keys(this.p),b=0;b<a.length;b++){var c=a[b];this.p[c]&&Z(this,k,Number(c))}this.p={}};function Z(a,b,c){c=a.l[c];c===U?b||a.c.O():c===T&&(b||F(a.c));81===c?b||a.c.W():a.Y[c]=!b};window.requestAnimationFrame||(window.requestAnimationFrame=window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame);function B(a){var b=document.getElementById("canvas");this.I=b.getContext("2d");b.width=a.width;b.height=a.height;this.canvas=b;this.T=m;this.R=0;this.S={};this.c=a}function ha(a,b){a.T=$(b,a.c.a.width,a.c.a.height,a.c.a.backgroundColor)}function ia(a){a.ja=$([],a.c.a.width,a.c.a.height)}
function $(a,b,c,d){var e=document.createElement("canvas"),f=e.getContext("2d");e.width=b;e.height=c;d&&(f.fillStyle=d,f.fillRect(0,0,b,c));a.forEach(function(a){f.drawImage(a.m,a.x,a.y,a.width,a.height)});return e}function ma(a,b,c,d){a.c.a.S[b]?(b=a.c.a.S[b],a.I.drawImage(a.c.images[b.images[(a.R/b.time|0)%b.images.length]],c,d)):a.I.drawImage(a.c.images[b],c,d)}
function la(a){function b(a){c.drawImage(a,d.r,d.s,d.width,d.height,0,0,d.width,d.height)}var c=a.I,d=a.c,e=d.images;a.R++;b(a.T);if(!d.o){var f="char";0===d.h?d.A&&(f+="Moving"):f=0<d.e?f+"Falling":f+"Jumping";f=1==d.direction?f+"Left":f+"Right";ma(a,f,d.f-d.r,d.g-d.s)}b(a.ja);d.v.forEach(function(a){a.visible&&(a.x+a.width>=d.r&&a.x<d.r+d.width&&a.y+a.height>=d.s&&a.y<d.s+d.height)&&c.drawImage(a.m,Math.round(a.x-d.r),Math.round(a.y-d.s),a.width,a.height)});d.o&&c.drawImage(e.Da,0,150)};Math.C=function(a){return(0<a)-(0>a)};Math.ra=function(a){return 0<a?Math.ceil(a):Math.floor(a)};Math.Ca=function(a){var b=Math.floor(a);return b+(Math.random()>a-b)};Math.xa=function(a){return function(b){return-1+4*Math.abs(b/a+0.25-Math.floor(b/a+0.75))}};Math.Ma=function(a){var b=Math.xa(a);return function(a){return Math.C(b(a))}};Math.H=function(a,b){return Math.C(a-b)};function na(a,b){var c;a.some(function(a,e){if(b(a))return c=e,k});return c}
Array.prototype.find=function(a){a=na(this,a);return a===h?h:this[a]};function H(a,b){var c=[];a.forEach(function(a){c=c.concat(b(a))});return c}function I(a,b){return a.filter(function(a){return-1===b.indexOf(a)})}Array.Na=function(a,b){for(var c=[],d=0;d<a;d++)c[d]=b;return c};function ga(a,b){return a.reduce(function(a,d){b(d)?a[0].push(d):a[1].push(d);return a},[[],[]])}Array.wa=function(a){return[].slice.call(a)};Function.G=function(a){return function(b){return b.file===a}};
Object.isArray=function(a){return a instanceof Array};Function.La=function(a){return function(b){return!a(b)}};Function.Fa=function(a,b,c){var d=a[b];a[b]=function(){d.apply(this,arguments);c.apply(this,arguments)}};Object.extend=function(a,b){for(var c=Object.keys(b),d,e=0;e<c.length;e++)d=c[e],a[d]=b[d];return a};Object.ha=function(a,b){for(var c=Object.keys(a),d=0;d<c.length;d++)a[c[d]]===b&&delete a[c[d]]};Object.Ja=function(a,b){return Object.extend(Object.extend({},a),b)};
Object.Qa=function(a){for(var b=Object.keys(a),c=[],d=0;d<b.length;d++)c.push(a[b[d]]);return c};function z(a){document.getElementById("warn").textContent+=a+"\n"}function J(a,b){if(!a)throw console.trace(),"Assert failed: "+b;}function aa(a,b){var c=new XMLHttpRequest;c.onreadystatechange=function(){4===c.readyState&&200===c.status&&b(c.responseText,a)};c.open("get",a,k);c.send("")}
function ea(a){Object.isArray(a)||(a=[a]);return["x","y"].reduce(function(a,c){return H(a,function(a){var b=a[c];return Object.isArray(b)?b.map(function(b){var e=Object.J(a);e[c]=b;return e}):[a]})},a)};
