'use strict';var h=void 0,l=!0,n=null,p=!1;function r(a){this.f=l;this.I={};try{if(!localStorage.getItem("version")&&(localStorage.setItem("version",a),!localStorage.getItem("version")))throw"grenade";}catch(b){this.f=p}this.f?Number(localStorage.getItem("version"))!==a&&(localStorage.clear(),console.log("Storage cleared because of game update to version "+a)):this.setItem("version",a)}r.prototype.setItem=function(a,b){var c=JSON.stringify(b);this.f?localStorage.setItem(a,c):this.I[a]=c};
r.prototype.removeItem=function(a){this.f?localStorage.removeItem(a):delete this.I[a]};r.prototype.getItem=function(a){return this.f?JSON.parse(localStorage.getItem(a)):this.I[a]?JSON.parse(this.I[a]):n};Object.Ga=function(a){function b(a,c,f,v){var m;if("object"==typeof a){if(a==n)return a;for(m in d)if(d[m]===a)return g.push({resolveTo:m,child:f,i:v}),n;d[c]=a;Object.isArray(a)?f=[]:(f={},f.__proto__=a.__proto__);for(m in a)f[m]=b(a[m],c+"["+m+"]",f,m);e[c]=f}else f=a;return f}var c,d={},e={},g=[];a=b(a,"*");for(c in g){var f=g[c];f&&(f.X&&f.oa in f.X)&&(f.X[f.oa]=e[f.Ua])}return a};var aa=800,ba=600,s="2up.js",t="no_audio",ca="last_level",u="state";window.addEventListener("load",function(){var a=new w;"localhost"===location.host&&window.Ca&&new LevelEditor(a)},p);
function w(){this.version=0.02;this.width=aa;this.height=ba;this.l=new r(this.version);this.l.f||x("localStorage not supported. Your game will not be saved.");this.sa=new y(this);this.B=new da(this);this.c=new z(!this.l.getItem(t));this.c.f||x("Your browser does not support HTML5 audio or ogg/vorbis");this.e=this.d=this.v=this.u=n;this.ba=Date.now();this.o=0;this.R=this.z=this.p=this.ja=this.P=this.G=this.q=this.g=this.direction=this.w=this.m=this.ia=n;this.S=l;this.D=n;this.images={};this.Z=this.na=
n;this.F=this.l.getItem(ca);var a=this;document.getElementById("mute_button").addEventListener("click",function(){a.K()},p);document.getElementById("reset_save").addEventListener("click",function(){a.F=s;a.l.removeItem(u);A(a,s)},p);this.F||(this.F=s);A(this,this.F)}function A(a,b){a.R=p;ea("levels/"+b+"?"+Math.random(),function(b){b=eval(b);if(!b)throw"level not found";a.a=b;fa(a,b)})}
function fa(a,b){function c(){f++;return function(){k++;B(q.B,k,f);f===k&&q.start()}}function d(){throw"loading a resource failed. Will not start";}var e=b.Va,g=Object.keys(b.images),f=0,k=0,q=a;a.c.path=b.Qa;a.a=b;C(a.c,a.a.qa,c(),d);C(a.c,a.a.ra,c(),d);g.forEach(function(a){var g=b.images[a],f=new Image;q.images[a]=f;f.onload=c();f.onerror=d;f.src=e+g});B(a.B,0,f)}w.prototype.start=function(){this.q=D(this.images.charHitmap);this.r=p;this.c.play(this.a.Da,l,l);E(this);this.R=l;this.S&&ga(this,this)};
function E(a){a.u=a.a.wa.x;a.v=a.a.wa.y;a.d=a.a.va.x;a.e=a.a.va.y;a.m=2;a.direction=0;a.r=p;a.D=p;a.w=l;a.g=0;a.c.stop(a.a.ka);a.ia=0;a.na={};a.Z=[];ha(a);var b=a.l.getItem(u);b&&a.a.Oa(a,b);a.a.C(a)}
function ha(a){var b=Object.O(a.a.G);a.G=[];a.P={};a.ja=[];a.p=[];a.z=[];var b=F(b,function(a){return ia(a.position).map(function(b){var c=Object.O(a);c.x=b.x;c.y=b.y;return c})}),c={};b.forEach(function(b){var e=c,g=b.$||!!b.id,f=b.shape,k=b.T,q=h,I=h,v=h,m=h,R="x y dynamic trigger image blocking killing id tickFunction zIndex position shape retrigger init".split(" "),e=e||{};G(Object.keys(b),R).length&&(console.log(G(Object.keys(b),R)),H(p,"Unkown properties"));b.k&&(q=a.images[b.k],H(q,"invalid image id"));
H(!b.L||!k,"an object cannot block and have a trigger at the same time");b.Na&&(H(!k,"an object cannot kill and have a trigger at the same time"),H(!b.L,"an object cannot kill and block at the same time"),k=a.Y.bind(a));if(f===h&&q&&(k||b.L||g))e[b.k]?f=e[b.k]:e[b.k]=f=new ja(q);f&&(I=f.width,v=f.height,e=f,e.h||(e.h=D(e.k)),m=e.h);g={x:b.x,y:b.y,width:I,height:v,$:g,visible:l,k:q,h:m,T:k,zIndex:b.zIndex||0,fa:!!b.fa,J:b.J,C:b.C};k&&(H(k instanceof Function,"trigger has to be a function"),H(f,"objects that kill or have a trigger require a shape"),
a.ja.push(g));b.k&&a.z.push(g);b.L&&(H(f,"objects that block require a shape"),a.p.push(g));a.G.push(g);b.id&&(H(!a.P[b.id],"id used twice"),a.P[b.id]=g);g.C&&g.C(a)});b=ka(a.z,function(a){return a.$});a.z=b[0];la(a.B,b[1]);ma(a.B)}w.prototype.K=function(){this.c.K();this.c.muted?this.l.setItem(t,1):this.l.removeItem(t)};w.prototype.Y=function(){this.r||(this.c.play(this.a.ka,p,l,0.3),this.r=l)};
var ga=function na(b,c){c.S=p;if(c.R){var d=c.a,e=Date.now();c.o+=e-c.ba;c.ba=e;500<=c.o&&(c.o=0);for(;c.o>=d.ea.xa;)oa(c),c.o-=d.ea.xa;pa(c.B);c.Z.forEach(function(b){b.call(c.a,c)});requestAnimationFrame(function(){na(c)})}else c.S=l};
function oa(a){var b=a.a.ea,c=a.sa.aa;a.a.J(a);a.G.forEach(function(b){b.J&&b.J.call(b,a);if(b.h&&b.T){var c=b.x>a.d+a.a.Fa||b.y>a.e+a.a.Ea||b.x+b.h.width<a.d||b.y+b.h.height<a.e?p:a.q.N(b.h,Math.round(b.x-a.d),Math.round(b.y-a.e));c&&(b.fa||!b.Aa)&&b.T.call(b,a);b.Aa=c}});a.ia++;if(!a.r)if(!c[J]!==!c[K]?(a.D=l,c[J]?(L(a,-b.ta),a.direction=1):c[K]&&(L(a,b.ta),a.direction=0)):a.D=p,0===a.m)c[M]&&(a.c.play(a.a.qa,p,p,0.6),a.m=1,a.w=l,a.g=b.pa,a.A=b.A),N(a,1)||(a.m=2,a.w=l);else{if(1===a.m){if(a.g+=
b.Ma,a.A--,!c[M]||0===a.A)a.m=2}else a.w&&c[M]&&(a.c.play(a.a.ra,p,p,0.6),a.m=1,a.w=p,a.g=b.pa/1.5,a.A=b.A),a.g=a.g<b.ma?a.g+b.Ha:b.ma;N(a,Math.ua(a.g))&&(0<a.g?(a.m=0,a.g=0,c[M]=p):a.g=0)}}function L(a,b){if(O(a.q,a.p,a.d+b,a.e))for(var c=Math.H(b);b;){if(a.d+=c,b-=c,O(a.q,a.p,a.d,a.e)){a.d-=c;break}}else a.d+=b}function N(a,b){if(!O(a.q,a.p,a.d,a.e+b))return a.e+=b,p;for(var c=Math.H(b);b;)if(a.e+=c,b-=c,O(a.q,a.p,a.d,a.e))return a.e-=c,l;return p};function z(a){this.muted=!a;this.f=l;window.Ba?(new Audio).canPlayType("audio/ogg; codecs=vorbis")||(this.f=p):this.f=p;this.t=[];this.Q=[]}
z.prototype.play=function(a,b,c,d,e){function g(a){return(a.c.ended||a.c.paused)!=!!c}if(this.f)if(this.muted)this.Q.push([new Date,Array.ya(arguments)]);else{var f=this.t.filter(Function.M(a)).find(g),k;f?k=f.c:(k=new Audio(this.path+a),this.t.push({c:k,file:a}));f=p;e!==h?k.duration&&k.duration<e&&(f=l):e=0;f||(d!==h&&(k.volume=d),4>k.readyState?k.addEventListener("loadedmetadata",function(){k.currentTime=e}):k.currentTime=e,k.loop=b,k.play())}};
function C(a,b,c,d){if(a.f&&!a.muted)if(a.t.find(Function.M(b)))c&&setTimeout(c,0);else{var e=new Audio(a.path+b);e.muted=a.muted;c&&(e.addEventListener("canplaythrough",c),d&&e.addEventListener("error",d));e.load();a.t.push({c:e,file:b})}else setTimeout(c,0)}z.prototype.stop=function(a){function b(a){a.c.pause()}this.f&&this.t.filter(Function.M(a)).forEach(b)};
z.prototype.K=function(){function a(a){a.c.muted=b}if(this.f){var b=this.muted=!this.muted;this.t.forEach(a)}if(!this.muted){var c=this;this.Q.forEach(function(a){a[1][4]=(Date.now()-a[0])/1E3;c.play.apply(c,a[1])});this.Q=[]}};function P(a,b){this.width=a;this.height=b;this.count=a*b;this.data=new Uint8Array(this.count)}function D(a){var b=a.width,c=a.height,d=new P(b,c),e=document.createElement("canvas"),g=e.getContext("2d");e.width=b;e.height=c;g.clearRect(0,0,b,c);g.drawImage(a,0,0);a=g.getImageData(0,0,b,c).data;for(b=0;b<d.count;b++)d.data[b]=0<a[4*b+3]|0;return d}
P.prototype.stringify=function(){for(var a="Bitmap  width="+this.width+" height="+this.height+"\n",b=0;b<this.height;b++){for(var c=0;c<this.width;c++)a+=String(this.data[b*this.width+c]);a+="\n"}return a};function Q(a,b,c,d,e){d=d||0;e=e||0;var g=Math.max(0,d),f=Math.max(0,e);d=Math.max(0,-d);e=Math.max(0,-e);return{ga:g,ha:f,ca:d,da:e,width:Math.max(0,Math.min(a.width-g,b-d)),height:Math.max(0,Math.min(a.height-f,c-e))}}
P.prototype.slice=function(a,b,c,d){c=Q(this,a,b,c,d);b=new P(a,b);d=c.ha*this.width+c.ga;for(var e=c.da*a+c.ca,g=0;g<c.height;g++){for(var f=0;f<c.width;f++)b.data[e]=this.data[d],d++,e++;d+=this.width-c.width;e+=a-c.width}return b};P.prototype.N=function(a,b,c){b=Q(this,a.width,a.height,b,c);c=b.da*a.width+b.ca;for(var d=b.ha*this.width+b.ga,e=0;e<b.height;e++){for(var g=0;g<b.width;g++){if(this.data[d]&&a.data[c])return l;c++;d++}c+=a.width-b.width;d+=this.width-b.width}return p};
function O(a,b,c,d){return b.some(function(b){return b.x>c+a.width||b.y>d+a.height||b.x+b.h.width<c||b.y+b.h.height<d?p:a.N(b.h,b.x-c,b.y-d)})};function ja(a){this.width=a.width;this.height=a.height;this.k=a;this.h=n};var J=37,K=39,M=32,S=82,T=77,U=84,V="keyboard_settings";
function y(a){this.s={};this.aa={};this.b=a;(a=a.l.getItem(V))?this.n=a:W(this);window.addEventListener("keydown",this.onkeydown.bind(this),p);window.addEventListener("keyup",this.onkeyup.bind(this),p);window.addEventListener("blur",this.onblur.bind(this),p);var b=this;document.getElementById("reset_keys").addEventListener("click",function(){W(b);b.b.l.setItem(V,b.n)},p);[["left",J],["right",K],["shoot",U],["jump",M],["mute",T],["restart",S]].forEach(function(a){var d=a[1],e=document.getElementById("keys"),
g=document.getElementById("press_key_msg");document.getElementById("change_"+a[0]).addEventListener("click",function(){e.style.display="none";g.style.display="block";window.addEventListener("keydown",function k(a){27!==a.which&&(Object.la(b.n,d),b.n[a.which]=d,b.b.l.setItem(V,b.n));window.removeEventListener("keydown",k,p);e.style.display="block";g.style.display="none";a.preventDefault()},p)},p)})}function W(a){a.n={38:38,40:40,37:J,39:K,32:M,82:S,77:T,84:U,81:81}}
function X(a,b){return!(b.ctrlKey||b.altKey||b.metaKey||b.target instanceof HTMLTextAreaElement||b.target instanceof HTMLInputElement||!a.n[b.which])}y.prototype.onkeydown=function(a){this.s[a.which]?a.preventDefault():X(this,a)&&(this.s[a.which]=l,Y(this,p,a.which),a.preventDefault())};y.prototype.onkeyup=function(a){X(this,a)&&(this.s[a.which]=p,Y(this,l,a.which),a.preventDefault())};
y.prototype.onblur=function(){for(var a=Object.keys(this.s),b=0;b<a.length;b++){var c=a[b];this.s[c]&&Y(this,l,Number(c))}this.s={}};function Y(a,b,c){c=a.n[c];c===T?b||a.b.K():c===S&&(b||E(a.b));81===c?b||a.b.Y():a.aa[c]=!b};window.requestAnimationFrame||(window.requestAnimationFrame=window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame);function da(a){var b=document.getElementById("canvas");this.j=b.getContext("2d");b.width=a.width;b.height=a.height;this.canvas=b;this.W=n;this.U=0;this.V={};this.b=a}function la(a,b){a.W=Z(b,a.b.a.width,a.b.a.height,a.b.a.backgroundColor)}function ma(a){a.Ja=Z([],a.b.a.width,a.b.a.height)}
function Z(a,b,c,d){var e=document.createElement("canvas"),g=e.getContext("2d");e.width=b;e.height=c;d&&(g.fillStyle=d,g.fillRect(0,0,b,c));a.forEach(function(a){g.drawImage(a.k,a.x,a.y,a.width,a.height)});return e}function qa(a,b,c,d){a.b.a.V[b]?(b=a.b.a.V[b],a.j.drawImage(a.b.images[b.images[(a.U/b.time|0)%b.images.length]],c,d)):a.j.drawImage(a.b.images[b],c,d)}
function pa(a){var b=a.j,c=a.b,d=c.images;a.U++;b.drawImage(a.W,c.u,c.v,c.width,c.height,0,0,c.width,c.height);if(!c.r){var e="char";0===c.m?c.D&&(e+="Moving"):e=0<c.g?e+"Falling":e+"Jumping";e=1==c.direction?e+"Left":e+"Right";qa(a,e,c.d-c.u,c.e-c.v)}c.z.forEach(function(a){a.visible&&(a.x+a.width>=c.u&&a.x<c.u+c.width&&a.y+a.height>=c.v&&a.y<c.v+c.height)&&b.drawImage(a.k,Math.round(a.x-c.u),Math.round(a.y-c.v),a.width,a.height)});c.r&&b.drawImage(d.Ka,0,150)}
function B(a,b,c){a.j.fillStyle="#000";a.j.fillRect(0,0,a.b.width,a.b.height);a.j.fillStyle="#fff";a.j.font="20px monospace";a.j.textAlign="center";a.j.fillText("Loading resources. Please wait ...",a.b.width>>1,100);a.j.fillText(b+" out of "+c,a.b.width>>1,140)};Math.H=function(a){return(0<a)-(0>a)};Math.ua=function(a){return 0<a?Math.ceil(a):Math.floor(a)};Math.Ia=function(a){var b=Math.floor(a);return b+(Math.random()>a-b)};Math.za=function(a){return function(b){return-1+4*Math.abs(b/a+0.25-Math.floor(b/a+0.75))}};Math.Sa=function(a){var b=Math.za(a);return function(a){return Math.H(b(a))}};Math.N=function(a,b){return Math.H(a-b)};function ra(a,b){var c;a.some(function(a,e){if(b(a))return c=e,l});return c}
Array.prototype.find=function(a){a=ra(this,a);return a===h?h:this[a]};function F(a,b){var c=[];a.forEach(function(a){c=c.concat(b(a))});return c}function G(a,b){return a.filter(function(a){return-1===b.indexOf(a)})}Array.Ta=function(a,b){for(var c=[],d=0;d<a;d++)c[d]=b;return c};function ka(a,b){return a.reduce(function(a,d){b(d)?a[0].push(d):a[1].push(d);return a},[[],[]])}Array.ya=function(a){return[].slice.call(a)};Function.M=function(a){return function(b){return b.file===a}};
Object.O=function $(b){if("object"===typeof b){if(b instanceof Array)return b.map($);if(b.__proto__)for(var c={__proto__:b.__proto__},d=Object.keys(b),e=0;e<d.length;e++)c[d[e]]=b[d[e]];else for(d in c={},b)c[d]=$(b[d]);return c}return b};Object.isArray=function(a){return a instanceof Array};Function.Ra=function(a){return function(b){return!a(b)}};Function.La=function(a,b,c){var d=a[b];a[b]=function(){d.apply(this,arguments);c.apply(this,arguments)}};
Object.extend=function(a,b){for(var c=Object.keys(b),d,e=0;e<c.length;e++)d=c[e],a[d]=b[d];return a};Object.la=function(a,b){for(var c=Object.keys(a),d=0;d<c.length;d++)a[c[d]]===b&&delete a[c[d]]};Object.Pa=function(a,b){return Object.extend(Object.extend({},a),b)};Object.Wa=function(a){for(var b=Object.keys(a),c=[],d=0;d<b.length;d++)c.push(a[b[d]]);return c};function x(a){document.getElementById("warn").textContent+=a+"\n"}function H(a,b){if(!a)throw console.trace(),"Assert failed: "+b;}
function ea(a,b){var c=new XMLHttpRequest;c.onreadystatechange=function(){4===c.readyState&&200===c.status&&b(c.responseText,a)};c.open("get",a,l);c.send("")}function ia(a){Object.isArray(a)||(a=[a]);return["x","y"].reduce(function(a,c){return F(a,function(a){var b=a[c];return Object.isArray(b)?b.map(function(b){var e=Object.O(a);e[c]=b;return e}):[a]})},a)};+function(){var a="";window.addEventListener("keyup",function(b){a=(a+b.which).substr(-14);83677278798377==a&&console.log("it works")})}();
