'use strict';var h=!0,k=null,n=!1;function p(a){this.e=h;try{if(!localStorage.getItem("version")&&(localStorage.setItem("version",a),!localStorage.getItem("version")))throw"bomb";}catch(b){this.e=n}this.e&&Number(localStorage.getItem("version"))!==a&&(localStorage.clear(),console.log("Storage cleared because of game update to version "+a))}p.prototype.setItem=function(a,b){this.e&&localStorage.setItem(a,JSON.stringify(b))};p.prototype.getItem=function(a){if(this.e)return JSON.parse(localStorage.getItem(a))};Object.F=function(a){function b(a,c,g,w){var l;if("object"==typeof a){if(a==k)return a;for(l in d)if(d[l]===a)return f.push({resolveTo:l,child:g,i:w}),k;d[c]=a;a instanceof Array?g=[]:(g={},g.__proto__=a.__proto__);for(l in a)g[l]=b(a[l],c+"["+l+"]",g,l);e[c]=g}else g=a;return g}var c,d={},e={},f=[];a=b(a,"*");for(c in f){var g=f[c];g&&(g.Q&&g.ga in g.Q)&&(g.Q[g.ga]=e[g.Da])}return a};var q=800,r=600,s="level1.js",t="last_level";window.addEventListener("load",function(){var a=new u;"localhost"===location.host&&window.ta&&new LevelEditor(a)},n);
function u(){this.version=0.01;this.width=q;this.height=r;this.w=new p(this.version);this.w.e||(document.getElementById("warn").textContent="localStorage not supported. Your game will not be saved.");this.ka=new v(this);this.I=new x(this);this.g=this.f=this.r=this.q=this.b=k;this.U=Date.now();this.m=0;this.A=this.u=this.z=this.L=this.H=this.B=this.t=this.d=this.direction=this.s=this.h=this.$=k;this.images={};this.fa=k;this.G=this.w.getItem(t);this.G||(this.G=s);y(this,this.G)}
function y(a,b){z("levels/"+b,function(c){c=eval(c);if(!c)throw"level not found";a.a=c;a.b=new A(c.ua);aa(a,c)})}u.prototype.start=function(){this.t=B(this.images.charHitmap);this.n=n;C(this);this.na||(this.na=h,ba(this,this))};function C(a){a.q=a.a.pa.x;a.r=a.a.pa.y;a.f=a.a.oa.x;a.g=a.a.oa.y;a.h=2;a.direction=0;a.n=n;a.A=n;a.s=h;a.d=0;a.b.play(a.a.aa,h,h);a.b.stop(a.a.ba);a.$=0;a.fa={};ca(a)}
function ca(a){var b=Object.F(a.a.B);a.B=[];a.H={};a.L=[];a.z=[];a.u=[];b=D(b,function(a){return da(a.position).map(function(b){var e=Object.F(a);e.f=b.x;e.g=b.y;return e})});b.forEach(function(c){var b=c.S||!!c.id,e=c.shape,f=c.K,g=void 0,m="posX posY dynamic trigger image blocking killing id tickFunction zIndex position shape".split(" ");E(Object.keys(c),m).length&&(console.log(E(Object.keys(c),m)),F(n,"Unkown properties"));c.l&&(g=a.images[c.l],F(g,"invalid image id"),void 0===e&&(e=new ea(g)));
F(!c.P||!f,"an object cannot block and have a trigger at the same time");c.Aa&&(F(!f,"an object cannot kill and have a trigger at the same time"),F(!c.P,"an object cannot kill and block at the same time"),f=a.R.bind(a));var m=c.f,S=c.g,T=e.width,w=e.height,l=e;l.j||(l.j=B(l.l));b={x:m,y:S,width:T,height:w,S:b,visible:h,l:g,j:l.j,K:f,zIndex:c.zIndex||0,C:c.C};f&&(F(f instanceof Function,"trigger has to be a function"),F(e,"objects that kill or have a trigger require a shape"),a.L.push(b));c.l&&a.u.push(b);
c.P&&(F(e,"objects that block require a shape"),a.z.push(b));a.B.push(b);c.id&&(F(!a.H[c.id],"id used twice"),a.H[c.id]=b)});b=fa(a.u,function(a){return a.S});a.u=b[0];ga(a.I,b[1]);ha(a.I)}u.prototype.R=function(){this.n||(this.b.stop(this.a.aa),this.b.play(this.a.ba,n,h),this.n=h)};
function aa(a,b){function c(){g++;return function(){g--;0===g&&m.start()}}function d(){throw"loading a resource failed. Will not start";}var e=b.Ea,f=Object.keys(b.images),g=0,m=a;a.a=b;G(a.b,a.a.ia,c(),d);G(a.b,a.a.ja,c(),d);f.forEach(function(a){var g=b.images[a],f=new Image;m.images[a]=f;f.onload=c();f.onerror=d;f.src=e+g})}var ba=function ia(b,c){var d=c.a,e=Date.now();c.m+=e-c.U;c.U=e;500<=c.m&&(console.log("logic skip"),c.m=0);for(;c.m>=d.X.qa;)ja(c),c.m-=d.X.qa,c.$++;ka(c.I);requestAnimationFrame(function(){ia(c)})};
function ja(a){var b=a.a.X,c=a.ka.T;a.a.C(a);a.L.forEach(function(b){b.j&&b.K&&H(a.t,b.j,Math.round(b.x-a.f),Math.round(b.y-a.g))&&b.K.call(b,a)});a.B.forEach(function(b){b.C&&b.C.call(b,a)});if(!a.n)if(!c[I]!==!c[J]?(a.A=h,c[I]?(K(a,-b.la),a.direction=1):c[J]&&(K(a,b.la),a.direction=0)):a.A=n,0===a.h)c[L]&&(a.b.play(a.a.ia,n,n),a.h=1,a.s=h,a.d=b.ha,a.v=b.v),M(a,1)||(a.h=2,a.s=h);else{if(1===a.h){if(a.d+=b.za,a.v--,!c[L]||0===a.v)a.h=2}else a.s&&c[L]&&(a.b.play(a.a.ja,n,n),a.h=1,a.s=n,a.d=b.ha/1.5,
a.v=b.v),a.d=a.d<b.da?a.d+b.wa:b.da;M(a,Math.ma(a.d))&&(0<a.d?(a.h=0,a.d=0,c[L]=n):a.d=0)}}function K(a,b){if(0!==b){var c=Math.J(b);for(a.t.slice(0,0,1,a.a.va);b;)if(a.f+=c,b-=c,N(a.t,a.z,a.f,a.g)){a.f-=c;break}}}function M(a,b){if(0===b)return n;for(var c=Math.J(b);b;)if(a.g+=c,b-=c,N(a.t,a.z,a.f,a.g))return a.g-=c,h;return n};function A(a){this.muted=n;this.e=h;this.path=a;window.sa?(new Audio).canPlayType("audio/ogg; codecs=vorbis")||(this.e=n):this.e=n;this.e=n;this.p=[]}A.prototype.play=function(a,b,c){function d(a){return(a.b.ended||a.b.paused)!=c}if(this.e){var e=this.p.filter(O(a)).find(d);e?(e=e.b,e.currentTime=0):(e=new Audio(this.path+a),e.muted=this.muted,this.p.push({b:e,file:a}));e.loop=b;e.play()}};
function G(a,b,c,d){if(a.e)if(a.p.find(O(b)))c&&setTimeout(c,0);else{var e=new Audio(a.path+b);e.muted=a.muted;c&&(e.addEventListener("canplaythrough",c),d&&e.addEventListener("error",d));e.load();a.p.push({b:e,file:b})}else setTimeout(c,0)}A.prototype.stop=function(a){function b(a){a.b.pause()}this.e&&this.p.filter(O(a)).forEach(b)};function la(a){function b(a){a.b.muted=c}if(a.e){var c=a.muted=!a.muted;a.p.forEach(b)}};function P(a,b){this.width=a;this.height=b;this.count=a*b;this.data=new Uint8Array(this.count)}function B(a){var b=a.width,c=a.height,d=new P(b,c),e=document.createElement("canvas"),f=e.getContext("2d");e.width=b;e.height=c;f.clearRect(0,0,b,c);f.drawImage(a,0,0);a=f.getImageData(0,0,b,c).data;for(b=0;b<d.count;b++)d.data[b]=0<a[4*b+3]|0;return d}
P.prototype.stringify=function(){for(var a="Bitmap  width="+this.width+" height="+this.height+"\n",b=0;b<this.height;b++){for(var c=0;c<this.width;c++)a+=String(this.data[b*this.width+c]);a+="\n"}return a};function Q(a,b,c,d,e){d=d||0;e=e||0;var f=Math.max(0,d),g=Math.max(0,e);d=Math.max(0,-d);e=Math.max(0,-e);return{Y:f,Z:g,V:d,W:e,width:Math.max(0,Math.min(a.width-f,b-d)),height:Math.max(0,Math.min(a.height-g,c-e))}}
P.prototype.slice=function(a,b,c,d){c=Q(this,a,b,c,d);b=new P(a,b);d=c.Z*this.width+c.Y;for(var e=c.W*a+c.V,f=0;f<c.height;f++){for(var g=0;g<c.width;g++)b.data[e]=this.data[d],d++,e++;d+=this.width-c.width;e+=a-c.width}return b};function H(a,b,c,d){c=Q(a,b.width,b.height,c,d);d=c.W*b.width+c.V;for(var e=c.Z*a.width+c.Y,f=0;f<c.height;f++){for(var g=0;g<c.width;g++){if(a.data[e]&&b.data[d])return h;d++;e++}d+=b.width-c.width;e+=a.width-c.width}return n}
function N(a,b,c,d){return b.some(function(b){return H(a,b.j,b.x-c,b.y-d)})};function ea(a){this.width=a.width;this.height=a.height;this.l=a;this.j=k};var I=37,J=39,L=32,R=82,U=77,V=84,W="keyboard_settings";
function v(a){this.o={};this.T={};this.c=a;(a=a.w.getItem(W))?this.k=a:X(this);window.addEventListener("keydown",this.onkeydown.bind(this),n);window.addEventListener("keyup",this.onkeyup.bind(this),n);window.addEventListener("blur",this.onblur.bind(this),n);var b=this;document.getElementById("reset_keys").addEventListener("click",function(){X(b);b.c.w.setItem(W,b.k)},n);[["left",I],["right",J],["shoot",V],["jump",L],["mute",U],["restart",R]].forEach(function(a){var d=a[1],e=document.getElementById("keys"),
f=document.getElementById("press_key_msg");document.getElementById("change_"+a[0]).addEventListener("click",function(){e.style.display="none";f.style.display="block";window.addEventListener("keydown",function m(a){27!==a.which&&(Object.ca(b.k,d),b.k[a.which]=d,b.c.w.setItem(W,b.k));window.removeEventListener("keydown",m,n);e.style.display="block";f.style.display="none";a.preventDefault()},n)},n)})}function X(a){a.k={38:38,40:40,37:I,39:J,32:L,82:R,77:U,84:V,81:81}}
function Y(a,b){return!(b.ctrlKey||b.altKey||b.metaKey||b.target instanceof HTMLTextAreaElement||b.target instanceof HTMLInputElement||!a.k[b.which])}v.prototype.onkeydown=function(a){this.o[a.which]?a.preventDefault():Y(this,a)&&(this.o[a.which]=h,Z(this,n,a.which),a.preventDefault())};v.prototype.onkeyup=function(a){Y(this,a)&&(this.o[a.which]=n,Z(this,h,a.which),a.preventDefault())};
v.prototype.onblur=function(){for(var a=Object.keys(this.o),b=0;b<a.length;b++){var c=a[b];this.o[c]&&Z(this,h,Number(c))}this.o={}};function Z(a,b,c){c=a.k[c];c===U?b||la(a.c.b):c===R&&(b||C(a.c));81===c?b||a.c.R():a.T[c]=!b};window.requestAnimationFrame||(window.requestAnimationFrame=window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame);function x(a){var b=document.getElementById("canvas");this.D=b.getContext("2d");b.width=a.width;b.height=a.height;this.canvas=b;this.O=k;this.M=0;this.N={};this.c=a}function ga(a,b){a.O=$(b,a.c.a.width,a.c.a.height,a.c.a.backgroundColor)}function ha(a){a.ea=$([],a.c.a.width,a.c.a.height)}
function $(a,b,c,d){var e=document.createElement("canvas"),f=e.getContext("2d");e.width=b;e.height=c;d&&(f.fillStyle=d,f.fillRect(0,0,b,c));a.forEach(function(a){f.drawImage(a.l,a.x,a.y,a.width,a.height)});return e}function ma(a,b,c,d){a.c.a.N[b]?(b=a.c.a.N[b],a.D.drawImage(a.c.images[b.images[(a.M/b.time|0)%b.images.length]],c,d)):a.D.drawImage(a.c.images[b],c,d)}
function ka(a){function b(a){c.drawImage(a,d.q,d.r,d.width,d.height,0,0,d.width,d.height)}var c=a.D,d=a.c,e=d.images;a.M++;b(a.O);if(!d.n){var f="char";0===d.h?d.A&&(f+="Moving"):f=0<d.d?f+"Falling":f+"Jumping";f=1==d.direction?f+"Left":f+"Right";ma(a,f,d.f-d.q,d.g-d.r)}b(a.ea);d.u.forEach(function(a){a.visible&&(a.x+a.width>=d.q&&a.x<d.q+d.width&&a.y+a.height>=d.r&&a.y<d.r+d.height)&&c.drawImage(a.l,Math.round(a.x-d.q),Math.round(a.y-d.r),a.width,a.height)});d.n&&c.drawImage(e.ya,0,150)};Math.J=function(a){return(0<a)-(0>a)};Math.ma=function(a){return 0<a?Math.ceil(a):Math.floor(a)};Math.xa=function(a){var b=Math.floor(a);return b+(Math.random()>a-b)};Math.ra=function(a){return function(b){return-1+4*Math.abs(b/a+0.25-Math.floor(b/a+0.75))}};Math.Ca=function(a){var b=Math.ra(a);return function(a){return Math.J(b(a))}};function na(a,b){var c;a.some(function(a,e){if(b(a))return c=e,h});return c}Array.prototype.find=function(a){a=na(this,a);return void 0===a?void 0:this[a]};
function D(a,b){var c=[];a.forEach(function(a){c=c.concat(b(a))});return c}function E(a,b){return a.filter(function(a){return-1===b.indexOf(a)})}function fa(a,b){return[a.filter(b),a.filter(oa(b))]}function O(a){return function(b){return b.file===a}}function oa(a){return function(b){return!a(b)}}Object.extend=function(a,b){for(var c=Object.keys(b),d,e=0;e<c.length;e++)d=c[e],a[d]=b[d];return a};Object.ca=function(a,b){for(var c=Object.keys(a),d=0;d<c.length;d++)a[c[d]]===b&&delete a[c[d]]};
Object.Ba=function(a,b){return Object.extend(Object.extend({},a),b)};Object.Fa=function(a){for(var b=Object.keys(a),c=[],d=0;d<b.length;d++)c.push(a[b[d]]);return c};function F(a,b){if(!a)throw console.trace(),"assert failed: "+b;}function z(a,b){var c=new XMLHttpRequest;c.onreadystatechange=function(){4===c.readyState&&200===c.status&&b(c.responseText,a)};c.open("get",a,h);c.send("")}
function da(a){a instanceof Array||(a=[a]);return["x","y"].reduce(function(a,c){return D(a,function(a){var b=a[c];return b instanceof Array?b.map(function(b){var e=Object.F(a);e[c]=b;return e}):[a]})},a)};
